[project]
name = "ai-engineering-fordham"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "google-genai>=1.47.0",
    "huggingface-hub>=0.23.0,<1.0",
    "ipykernel>=6.31.0",
    "litellm>=1.81.1",
    "numpy>=2.0.2",
    "pydantic>=2.12.5",
    "pystemmer>=3.0.0",
    "python-dotenv>=1.2.1",
]
